version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: docker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
